service: IMAGE-REKOGNITION

provider: 
  name: aws
  runtime: nodejs16.x
  stage: test
  environment:
    ACCESS_KEY_ID: ${file(./serverless.env.yml):ACCESS_KEY_ID}
    SECRET_ACCESS_KEY: ${file(./serverless.env.yml):SECRET_ACCESS_KEY}

plugins:
  - serverless-webpack
  - serverless-offline

functions:
  rekognition:
    handler: src/api.default
    events:
      - http: 'GET /labels'

custom:
  serverless-offline:
    httpPort: 3001